### PR TITLE
Added setup.py and .pot file

### LINKED ISSUE #3: setup.py is missing

### PR DESCRIPTION
**Pull request by yell0wfl4sh**
Fixes #3 

- added *.gitignore* file
- added *po/ShowJPEG.pot* file
- made changes in *activity/activity.info* and *activity.py* to ensure ```python setup.py build``` and ```sugar-activity .``` works properly

@quozl please review!

### CODE REVIEW

**Comment by yell0wfl4sh** [comment]
Also fixes #2 

- ```MANIFEST``` was not mentioned any where in the source code; checked by ```git grep "MANIFEST"``` and manually also
- ```python setup.py build``` and ```sugar-activity .``` also works fine

**Comment by quozl** [comment]
Thanks.  Reviewed.

- [x] your `setup.py` uses our GTK+ 2 toolkit, but `activity.py` uses our GTK+ 3 toolkit; it should import from `sugar3`,
- [x] if you are in agreement, please license and assign your copyright for `setup.py` to the author of `activity.py`, as it makes things clearer later,
- [ ] please internationalise all strings seen by a user, such as the [starting message](https://github.com/sugarlabs/ShowJPEG/blob/master/show.py#L248).

**Comment by yell0wfl4sh** [comment]
- [x] setup.py now uses GTK+ 3 toolkit
- [x] added license and copyright to setup.py to the author of activity.py, (not sure if done correctly!)
- [x] internationalised all strings seen by a user

**Comment by quozl** [comment]
Sorry, I missed that you had not wrapped the strings with gettext, please check?

**Pull request merged**
